[build]
  publish = "public"
  command = "echo 'Site déjà prêt'"

[build.environment]
  NODE_VERSION = "18"

# Configuration des headers pour sitemap.xml
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Cache-Control = "public, max-age=86400"

# Configuration des headers pour robots.txt
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"
    Cache-Control = "public, max-age=3600"

# Configuration générale des headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirection www vers non-www
[[redirects]]
  from = "https://www.iptvsmarterpros.com/*"
  to = "https://iptvsmarterpros.com/:splat"
  status = 301
  force = true

# Page 404 personnalisée
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 