[build]
  publish = "public"
  command = "echo 'Static site ready'"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Variables d'environnement pour l'email - NAMECHEAP PRIVATE EMAIL
[context.production.environment]
  SMTP_HOST = "mail.privateemail.com"
  SMTP_PORT = "465"
  SMTP_USER = "votre-email@votre-domaine.com"
  SMTP_PASS = "votre-mot-de-passe-app-namecheap"
  ADMIN_EMAIL = "votre-email@votre-domaine.com"

[context.deploy-preview.environment]
  SMTP_HOST = "mail.privateemail.com"
  SMTP_PORT = "465"
  SMTP_USER = "votre-email@votre-domaine.com"
  SMTP_PASS = "votre-mot-de-passe-app-namecheap"
  ADMIN_EMAIL = "votre-email@votre-domaine.com"

# Headers spécifiques pour sitemap.xml
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Cache-Control = "public, max-age=86400"
    X-Robots-Tag = "all"

# Headers spécifiques pour robots.txt  
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"
    Cache-Control = "public, max-age=3600"
    X-Robots-Tag = "all"

# Headers pour les fonctions API
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Configuration générale des headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Les redirections sont gérées par le fichier _redirects 