[build]
  command = "npm install"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirection de la version sans www vers la version avec www
[[redirects]]
  from = "https://iptvsmarterpros.com/*"
  to = "https://www.iptvsmarterpros.com/:splat"
  status = 301
  force = true

# Redirection HTTP vers HTTPS
[[redirects]]
  from = "http://iptvsmarterpros.com/*"
  to = "https://www.iptvsmarterpros.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.iptvsmarterpros.com/*"
  to = "https://www.iptvsmarterpros.com/:splat"
  status = 301
  force = true

# Configuration des en-têtes pour le SEO et la sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "upgrade-insecure-requests"

# Configuration spécifique pour le sitemap et robots.txt
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Robots-Tag = "all"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    X-Robots-Tag = "all" 